
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<Greeting> {
    return await TAURI_INVOKE("greet", { name });
},
async getMonitors() : Promise<Result<MonitorData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_monitors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takeScreenshot(monitorId: string, resizeX: number, resizeY: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_screenshot", { monitorId, resizeX, resizeY }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveMouse(monitorId: string, x: number, y: number, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_mouse", { monitorId, x, y, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mouseClick(monitorId: string, side: string, x: number | null, y: number | null, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mouse_click", { monitorId, side, x, y, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCursorPosition(monitorId: string) : Promise<Result<[number, number], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cursor_position", { monitorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async typeText(text: string, monitorId: string, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("type_text", { text, monitorId, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scroll(monitorId: string, direction: string, amount: number, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scroll", { monitorId, direction, amount, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pressKey(key: string, monitorId: string, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("press_key", { key, monitorId, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async wait(duration: number, monitorId: string, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wait", { duration, monitorId, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mouseDrag(monitorId: string, startX: number, startY: number, endX: number, endY: number, autoScreenshot: boolean | null, screenshotWidth: number | null, screenshotHeight: number | null) : Promise<Result<ActionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mouse_drag", { monitorId, startX, startY, endX, endY, autoScreenshot, screenshotWidth, screenshotHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActionResult = { success: boolean; message: string; screenshot: string | null }
export type Greeting = { message: string }
export type MonitorData = { id: string; is_primary: boolean; name: string; width: number; height: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
